language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/setup-oracle-jdk6.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/build-nablarch.sh -p ci
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: UTYI0lR1/S+OTfSnc4LMfwIl1DkYQZPbg1GRpmyaKZhRHkXBBgZctGVfobqewxNviV8lfjkGi0x09jah1im2S6XSPa4hAuITavAaK+rKKG44E136ecdvWDlJSL4iJPUC2ftMCEso9Npbr0omRhe5Ah02vrw9eMXnda+EU0+EfBEAw6o8KonSyKjze5KBrnF84vY/X1c0LZS+pa/YNvHfM+ABirVNnkzNQVoUO2X1U9Axi+hXI/6S4Rqu03w3OZBHNwk0FNz3wjXYvJLBYnB+FIjuuUgeQuPDUhVGXz8WbutgNVjdgL9h0/QD+Qv7I1lZtCSmL74K1JL5g3G62/ou6kZftstlhwPqMvv23nAalOTcctr+MzJx9yWM8d+zlXS2c5Cy6yXQDaZV/1/ubbGcb6bqwWlm0PGiwGF2uMUbCpsTF8E5A9bRfweHoq5H0GRf6F+/GQDeB5VKwIV4+XR2/fatuwAY/Fd8d3er/4v+n6wvbjvDiVKjno2Y4ij+0IHXxf2XZbrr5n9JZEKvZJLXIDs6dt9aLdGdeaHeoVMoDORvVQO5sZM0aJi9S62uCZpyr0uW7d4DM6v60VmqkEJLoUF1DYxPzFQ0GdcvHIvD8S1rw5xuQk3Ym8VRbg/jov1VxM7+Af0K2uOvg+WeIkwjpixI+BQGeXW/1bLIjnmQ6sk=
